//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EJ07.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class SettingsEJ07 : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsEJ07 defaultInstance = ((SettingsEJ07)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsEJ07())));
        
        public static SettingsEJ07 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rivera")]
        public string AESSal {
            get {
                return ((string)(this["AESSal"]));
            }
            set {
                this["AESSal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pFlEmEL5_¡4#pF")]
        public string AESContraseña {
            get {
                return ((string)(this["AESContraseña"]));
            }
            set {
                this["AESContraseña"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ADFTHUJIKOLP")]
        public string EngConexiones {
            get {
                return ((string)(this["EngConexiones"]));
            }
            set {
                this["EngConexiones"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>A</string>\r\n  <string>A</string>\r\n  <string>A</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection EngAnillos {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["EngAnillos"]));
            }
            set {
                this["EngAnillos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>1</string>\r\n  <string>2</string>\r\n  <string>3</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection EngRotores {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["EngRotores"]));
            }
            set {
                this["EngRotores"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int CesDesplazamiento {
            get {
                return ((int)(this["CesDesplazamiento"]));
            }
            set {
                this["CesDesplazamiento"] = value;
            }
        }
    }
}
